name: Electron-forge packages release

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
    
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os:
          [
            { name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos', image: 'macos-latest' },
            { name: 'linux-arm64', image: 'ubuntu-latest', arch: 'arm64' }
          ]
        node-version: [22.4.x]
        
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.os.arch || 'x64' }}

      - name: Set up QEMU
        if: matrix.os.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - run: npm ci

      - name: Running npm run build..
        run: npm run build

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

    permissions:
      contents: write
      id-token: write
      packages: write