name: Electron-forge packages release

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
    
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos
          - os: ubuntu-latest-arm64
            name: linux-arm64
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Use Node.js '22.4.x'
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.x'

      - run: npm ci

      - name: Running npm run build..
        run: npm run build

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

    permissions:
      contents: write
      id-token: write
      packages: write